export const SITE_NAME = "oxabags"
export const SITE_URL = "https://www.oxabags.com/"
export const SITE_DESCRIPTION = "Manufacturer, Wholesaler & Exporter of Jute bags, Cotton Bag for Corporate Events & Exhibitions"
export const SITE_KEYWORDS = "Jute bags, Cotton Bag, Canvas Bags, File Folders, Denim Bags, Pouches"
export const SITE_CATEGORY = "Shopping"
export const SITE_IMAGE = "https://www.oxabags.com/og.webp"
export const OWNER_NAME = "Kuldeep Gupta"
export const OWNER_EMAIL = "info@oxabags.com"
export const OWNER_PHONE_1 = "9868151526"
export const OWNER_PHONE_2 = "9811365888"
export const COMPANY_NAME = "Aman Enterprises"
export const COMPANY_ADDRESS = "G-211, UPSIDC Industrial Area Phase-1 M. G. Road, Dholana GHAZIABAD -201015, UP"

